/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexionbbdd;

/**
 *
 * @author aghsk
 */
public class Ventana extends javax.swing.JFrame {
    
    PoolConexiones manager = new PoolConexiones();

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConectar = new javax.swing.JButton();
        jButtonDesconectar = new javax.swing.JButton();
        jButtonBorrarTablaGrupo = new javax.swing.JButton();
        jButtonCrearTablaGrupo = new javax.swing.JButton();
        jButtonAddColumnaTablaGrupo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonConectar.setText("Conectar");
        jButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConectarActionPerformed(evt);
            }
        });

        jButtonDesconectar.setText("Desconectar");
        jButtonDesconectar.setEnabled(false);
        jButtonDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesconectarActionPerformed(evt);
            }
        });

        jButtonBorrarTablaGrupo.setText("Borrar Tabla Grupo");
        jButtonBorrarTablaGrupo.setEnabled(false);
        jButtonBorrarTablaGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTablaGrupoActionPerformed(evt);
            }
        });

        jButtonCrearTablaGrupo.setText("Crear Tabla Grupo");
        jButtonCrearTablaGrupo.setEnabled(false);
        jButtonCrearTablaGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearTablaGrupoActionPerformed(evt);
            }
        });

        jButtonAddColumnaTablaGrupo.setText("Añadir Año a Grupo");
        jButtonAddColumnaTablaGrupo.setEnabled(false);
        jButtonAddColumnaTablaGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddColumnaTablaGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButtonConectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jButtonDesconectar)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButtonBorrarTablaGrupo)
                .addGap(33, 33, 33)
                .addComponent(jButtonCrearTablaGrupo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddColumnaTablaGrupo)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConectar)
                    .addComponent(jButtonDesconectar))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrarTablaGrupo)
                    .addComponent(jButtonCrearTablaGrupo))
                .addGap(28, 28, 28)
                .addComponent(jButtonAddColumnaTablaGrupo)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConectarActionPerformed
        // TODO add your handling code here:
        manager.conection();
        jButtonConectar.setEnabled(false);
        jButtonDesconectar.setEnabled(true);
        jButtonBorrarTablaGrupo.setEnabled(true);
        jButtonAddColumnaTablaGrupo.setEnabled(true);
        jButtonDesconectar.setEnabled(true);

    }//GEN-LAST:event_jButtonConectarActionPerformed

    private void jButtonDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesconectarActionPerformed
        // TODO add your handling code here:

        manager.cerrarConexion();
        jButtonConectar.setEnabled(true);
        jButtonDesconectar.setEnabled(false);
        /*
        if (retorno == 0) {
            System.out.println("Desconectado de la BBDD");
        } else {
            System.out.println("Error en la desconexionF");
        }*/
    }//GEN-LAST:event_jButtonDesconectarActionPerformed

    private void jButtonBorrarTablaGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTablaGrupoActionPerformed
        // TODO add your handling code here:
        manager.borrarTablaGrupo();
        jButtonCrearTablaGrupo.setEnabled(true);
        jButtonAddColumnaTablaGrupo.setEnabled(false);
    }//GEN-LAST:event_jButtonBorrarTablaGrupoActionPerformed

    private void jButtonCrearTablaGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearTablaGrupoActionPerformed
        // TODO add your handling code here:
        manager.crearTablaGrupo();
        jButtonAddColumnaTablaGrupo.setEnabled(true);
        jButtonCrearTablaGrupo.setEnabled(false);
    }//GEN-LAST:event_jButtonCrearTablaGrupoActionPerformed

    private void jButtonAddColumnaTablaGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddColumnaTablaGrupoActionPerformed
        // TODO add your handling code here:
        manager.addColumna();
        jButtonAddColumnaTablaGrupo.setEnabled(false);
    }//GEN-LAST:event_jButtonAddColumnaTablaGrupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddColumnaTablaGrupo;
    private javax.swing.JButton jButtonBorrarTablaGrupo;
    private javax.swing.JButton jButtonConectar;
    private javax.swing.JButton jButtonCrearTablaGrupo;
    private javax.swing.JButton jButtonDesconectar;
    // End of variables declaration//GEN-END:variables
}
