/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexionbbdd;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aghsk
 */
public class VentanaAlbumCancion extends javax.swing.JFrame {

    PoolConexiones manager = new PoolConexiones();

    /**
     * Creates new form VentanaAlbumCancion
     */
    public VentanaAlbumCancion() {
        initComponents();
        conectarseADiscográfica();

        //MOSTRAR TABLAS
        mostrarTablaAlbum();
        mostrarTablaCanciones();

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                manager.cerrarConexion();

                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Album = new javax.swing.JPanel();
        jTextFieldNombreAlbum = new javax.swing.JTextField();
        jTextFieldDiscografica = new javax.swing.JTextField();
        jTextFieldLider = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jButtonBorrarTablaAlbum = new javax.swing.JButton();
        jButtonCrearTablaAlbum = new javax.swing.JButton();
        jButtonInsertarAlbum = new javax.swing.JButton();
        jTextFieldIdAlbum = new javax.swing.JTextField();
        jTextFieldEliminarAlbum = new javax.swing.JTextField();
        jButtonEliminarAlbumIndividual = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAlbum = new javax.swing.JTable();
        Cancion = new javax.swing.JPanel();
        jButtonBorrarTablaCancion = new javax.swing.JButton();
        jButtonCrearTablaCancion = new javax.swing.JButton();
        jButtonInsertarCancion = new javax.swing.JButton();
        jTextFieldIdCancion = new javax.swing.JTextField();
        jTextFieldNombreCancion = new javax.swing.JTextField();
        jTextFieldDuracion = new javax.swing.JTextField();
        jTextFieldFechaLanzamieto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelInfo1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAlbumCancion = new javax.swing.JTextField();
        jTextFieldEliminarCancion = new javax.swing.JTextField();
        jButtonEliminarCancion = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCancion = new javax.swing.JTable();
        jButtonActualizarTablas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Id:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Discografica:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Lider:");

        jLabelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInfo.setText("Sin conexión a la BBDD Discográfica.");

        jButtonBorrarTablaAlbum.setText("Borrar Tabla Album");
        jButtonBorrarTablaAlbum.setEnabled(false);
        jButtonBorrarTablaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTablaAlbumActionPerformed(evt);
            }
        });

        jButtonCrearTablaAlbum.setText("Crear Tabla Album");
        jButtonCrearTablaAlbum.setEnabled(false);
        jButtonCrearTablaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearTablaAlbumActionPerformed(evt);
            }
        });

        jButtonInsertarAlbum.setText("Insertar Album");
        jButtonInsertarAlbum.setEnabled(false);
        jButtonInsertarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarAlbumActionPerformed(evt);
            }
        });

        jButtonEliminarAlbumIndividual.setText("Eliminar Album");

        jTableAlbum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableAlbum);

        javax.swing.GroupLayout AlbumLayout = new javax.swing.GroupLayout(Album);
        Album.setLayout(AlbumLayout);
        AlbumLayout.setHorizontalGroup(
            AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addComponent(jLabelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlbumLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AlbumLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldLider, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AlbumLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDiscografica, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AlbumLayout.createSequentialGroup()
                                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldIdAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonInsertarAlbum))))
                        .addGap(131, 131, 131))
                    .addGroup(AlbumLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jTextFieldEliminarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEliminarAlbumIndividual)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlbumLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCrearTablaAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBorrarTablaAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        AlbumLayout.setVerticalGroup(
            AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlbumLayout.createSequentialGroup()
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AlbumLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCrearTablaAlbum)
                            .addComponent(jButtonBorrarTablaAlbum))
                        .addGap(71, 71, 71)
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEliminarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEliminarAlbumIndividual))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonInsertarAlbum)
                        .addGap(18, 18, 18)
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIdAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDiscografica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldLider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AlbumLayout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addComponent(jLabelInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Album", Album);

        jButtonBorrarTablaCancion.setText("Borrar Tabla Cancion");
        jButtonBorrarTablaCancion.setEnabled(false);
        jButtonBorrarTablaCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTablaCancionActionPerformed(evt);
            }
        });

        jButtonCrearTablaCancion.setText("Crear Tabla Cancion");
        jButtonCrearTablaCancion.setEnabled(false);
        jButtonCrearTablaCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearTablaCancionActionPerformed(evt);
            }
        });

        jButtonInsertarCancion.setText("Insertar Cancion");
        jButtonInsertarCancion.setEnabled(false);
        jButtonInsertarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarCancionActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nombre:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Id:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Duracion:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Release:");

        jLabelInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInfo1.setText("Sin conexión a la BBDD Discográfica.");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Album:");

        jButtonEliminarCancion.setText("Eliminar Cancion");

        jTableCancion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableCancion);

        jButtonActualizarTablas.setText("Actualizar Datos");
        jButtonActualizarTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarTablasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CancionLayout = new javax.swing.GroupLayout(Cancion);
        Cancion.setLayout(CancionLayout);
        CancionLayout.setHorizontalGroup(
            CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CancionLayout.createSequentialGroup()
                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CancionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)))
                    .addGroup(CancionLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButtonActualizarTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonInsertarCancion)
                        .addGroup(CancionLayout.createSequentialGroup()
                            .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(14, 14, 14)
                            .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldIdCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addComponent(jTextFieldNombreCancion)
                                .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldFechaLanzamieto)
                                .addComponent(jTextFieldAlbumCancion))))
                    .addGroup(CancionLayout.createSequentialGroup()
                        .addComponent(jTextFieldEliminarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CancionLayout.createSequentialGroup()
                        .addComponent(jButtonCrearTablaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorrarTablaCancion)))
                .addGap(30, 30, 30))
        );
        CancionLayout.setVerticalGroup(
            CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearTablaCancion)
                    .addComponent(jButtonActualizarTablas)
                    .addComponent(jButtonBorrarTablaCancion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabelInfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CancionLayout.createSequentialGroup()
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEliminarCancion)
                            .addComponent(jTextFieldEliminarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonInsertarCancion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldAlbumCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIdCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFechaLanzamieto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(CancionLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cancion", Cancion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarAlbumActionPerformed
        // INSERTAR ALBUM EN LA BBDD
        manager.insertarAlbum(jTextFieldIdAlbum.getText(), jTextFieldNombreAlbum.getText(), jTextFieldDiscografica.getText(), jTextFieldLider.getText());
        jLabelInfo.setText("Album insertado correctamente");
        jLabelInfo1.setText("Album insertado correctamente");
    }//GEN-LAST:event_jButtonInsertarAlbumActionPerformed

    private void jButtonCrearTablaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearTablaAlbumActionPerformed
        // CREAR LA TABLA ALBUM
        manager.crearTablaAlbum();
        jButtonCrearTablaAlbum.setEnabled(false);
        jLabelInfo.setText("La Tabla album a sido creada correctamente");
        jLabelInfo1.setText("La Tabla album a sido creada correctamente");
    }//GEN-LAST:event_jButtonCrearTablaAlbumActionPerformed

    private void jButtonBorrarTablaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTablaAlbumActionPerformed
        // BORRAR LA TABLA ALBUM
        manager.borrarTablaAlbum();
        jButtonCrearTablaAlbum.setEnabled(true);
        jLabelInfo.setText("La Tabla album a sido borrada correctamente");
        jLabelInfo1.setText("La Tabla album a sido borrada correctamente");
    }//GEN-LAST:event_jButtonBorrarTablaAlbumActionPerformed

    private void jButtonInsertarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarCancionActionPerformed
        // INSERTAR CANCION EN LA BBDD
        manager.insertarCancion(jTextFieldIdCancion.getText(), jTextFieldNombreCancion.getText(), jTextFieldDuracion.getText(), jTextFieldFechaLanzamieto.getText(), jTextFieldAlbumCancion.getText());
        jLabelInfo.setText("Cancion insertada correctamente");
        jLabelInfo1.setText("Cancion insertada correctamente");
    }//GEN-LAST:event_jButtonInsertarCancionActionPerformed

    private void jButtonCrearTablaCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearTablaCancionActionPerformed
        // CREAR TABLA CANCION
        manager.crearTablaCancion();
        jButtonCrearTablaCancion.setEnabled(false);
        jLabelInfo.setText("La Tabla cancion a sido creada correctamente");
        jLabelInfo1.setText("La Tabla cancion a sido creada correctamente");
    }//GEN-LAST:event_jButtonCrearTablaCancionActionPerformed

    private void jButtonBorrarTablaCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTablaCancionActionPerformed
        // BORRAR TABLA CANCION
        manager.borrarTablaCancion();
        jButtonBorrarTablaCancion.setEnabled(false);
        jButtonCrearTablaCancion.setEnabled(true);
        jLabelInfo.setText("La Tabla cancion a sido borrada correctamente");
        jLabelInfo1.setText("La Tabla cancion a sido creada correctamente");
    }//GEN-LAST:event_jButtonBorrarTablaCancionActionPerformed

    private void jButtonActualizarTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarTablasActionPerformed
        // ACTUALIZAR LAS TABLAS
        mostrarTablaAlbum();
        mostrarTablaCanciones();
    }//GEN-LAST:event_jButtonActualizarTablasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAlbumCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAlbumCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAlbumCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAlbumCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAlbumCancion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Album;
    private javax.swing.JPanel Cancion;
    private javax.swing.JButton jButtonActualizarTablas;
    private javax.swing.JButton jButtonBorrarTablaAlbum;
    private javax.swing.JButton jButtonBorrarTablaCancion;
    private javax.swing.JButton jButtonCrearTablaAlbum;
    private javax.swing.JButton jButtonCrearTablaCancion;
    private javax.swing.JButton jButtonEliminarAlbumIndividual;
    private javax.swing.JButton jButtonEliminarCancion;
    private javax.swing.JButton jButtonInsertarAlbum;
    private javax.swing.JButton jButtonInsertarCancion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelInfo1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableAlbum;
    private javax.swing.JTable jTableCancion;
    private javax.swing.JTextField jTextFieldAlbumCancion;
    private javax.swing.JTextField jTextFieldDiscografica;
    private javax.swing.JTextField jTextFieldDuracion;
    private javax.swing.JTextField jTextFieldEliminarAlbum;
    private javax.swing.JTextField jTextFieldEliminarCancion;
    private javax.swing.JTextField jTextFieldFechaLanzamieto;
    private javax.swing.JTextField jTextFieldIdAlbum;
    private javax.swing.JTextField jTextFieldIdCancion;
    private javax.swing.JTextField jTextFieldLider;
    private javax.swing.JTextField jTextFieldNombreAlbum;
    private javax.swing.JTextField jTextFieldNombreCancion;
    // End of variables declaration//GEN-END:variables

    //PARA CONECTARSE A LA BBDD AL INICIAR LA APP
    private void conectarseADiscográfica() {
        manager.conection();
        ///
        jButtonBorrarTablaAlbum.setEnabled(true);
        // jButtonAddColumnaTablaAlbum.setEnabled(true);
        jButtonInsertarAlbum.setEnabled(true);
        jButtonInsertarAlbum.setEnabled(true);
        ///
        jButtonBorrarTablaCancion.setEnabled(true);
        // jButtonAddColumnaTablaCancion.setEnabled(true);
        jButtonInsertarCancion.setEnabled(true);
        jButtonInsertarCancion.setEnabled(true);
        jLabelInfo.setText("Conectado con exito a Discográfica!");
        jLabelInfo1.setText("Conectado con exito a Discográfica!");
    }

    //PARA MOSTRAR LAS TABLAS
    private void mostrarTablaAlbum() {
        //Se inserta el modelo de la tabla
        DefaultTableModel modelo = new DefaultTableModel();
        //AQUI SE INSERTA LA CONSULTA QUE VA EN POOLCONEXIONES
        ResultSet rs = (ResultSet) manager.mostrarTabla("SELECT * FROM album ORDER BY id");

        try {
            //COGEMOS LOS NOMBRES DE LA COLUMNAS
            ResultSetMetaData metaDatos = rs.getMetaData();

            int numeroColumnas = metaDatos.getColumnCount();

            String[] etiquetas = new String[numeroColumnas];

            for (int i = 0; i < numeroColumnas; i++) {
                etiquetas[i] = metaDatos.getColumnLabel(i + 1);
                modelo.setColumnIdentifiers(etiquetas);
            }

            while (rs.next()) {
                //COGEMOS LOS DATOS DE LAS FILAS
                modelo.addRow(new Object[]{rs.getInt("id"), rs.getString("Nombre_Album"),
                    rs.getString("Discografica"), rs.getString("Lider")});
            }
            //SE INSERTAN LOS DATOS EN LA TABLA
            jTableAlbum.setModel(modelo);
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }

    }

    private void mostrarTablaCanciones() {
        //Ponemos el model a la tabla
        DefaultTableModel modelo = new DefaultTableModel();
        try {
            //Hacemos la consulta
            ResultSet rs = (ResultSet) manager.mostrarTabla("SELECT * FROM cancion ORDER BY id");
            //Obtenemos los nombres de las columnas
            ResultSetMetaData metaDatos = rs.getMetaData();

            int numeroColumnas = metaDatos.getColumnCount();
            // Se crea un array de etiquetas para rellenar
            String[] etiquetas = new String[numeroColumnas];

            // Se obtiene cada una de las etiquetas para cada columna
            for (int i = 0; i < numeroColumnas; i++) {
                etiquetas[i] = metaDatos.getColumnLabel(i + 1);
                modelo.setColumnIdentifiers(etiquetas);
            }
            while (rs.next()) {
                //Obtenemos los datos de las filas
                modelo.addRow(new Object[]{rs.getInt("id"), rs.getString("Nombre"),
                    rs.getString("Duracion"), rs.getDate("Release_Date"), rs.getString("album.Nombre_Album")});
            }
            //Rellenamos la tabla con los datos.
            jTableCancion.setModel(modelo);
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }

    }
}
