/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexionbbdd;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aghsk
 */
public class VentanaAlbumCancion extends javax.swing.JFrame {

    //PARA ACCEDER A LOS METODOS DE POOLCONEXIONES
    PoolConexiones manager = new PoolConexiones();

    /**
     * Creates new form VentanaAlbumCancion
     */
    public VentanaAlbumCancion() {
        initComponents();
        conectarseADiscográfica();

        //MOSTRAR TABLAS
        mostrarTablaAlbum();
        mostrarTablaCancion();
        //INSERTAR EL METODO EDITAR PARA QUE FUNCIONE EL RELLENAR CAMPOS
        //AL SELECCIONAR UN DATO DE UNA TABLA
        editar();
        //WINDOWS LISTENER QUE DETECTA CUANDO SE CIERRA LA VENTANA 
        //SI SE CIERRA TE DESCONECTAS DE LA BBDD
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                manager.cerrarConexion();
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Album = new javax.swing.JPanel();
        jTextFieldNombreAlbum = new javax.swing.JTextField();
        jTextFieldDiscografica = new javax.swing.JTextField();
        jTextFieldLider = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jButtonInsertarAlbum = new javax.swing.JButton();
        jTextFieldEliminarAlbum = new javax.swing.JTextField();
        jButtonEliminarAlbumIndividual = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAlbum = new javax.swing.JTable();
        jTextFieldIdAlbum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonCambiarAlbum = new javax.swing.JButton();
        jTextFieldGenero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonAlterAlbum = new javax.swing.JButton();
        jComboBoxAlterAlbum = new javax.swing.JComboBox<>();
        Cancion = new javax.swing.JPanel();
        jButtonBorrarTablaCancion = new javax.swing.JButton();
        jButtonInsertarCancion = new javax.swing.JButton();
        jTextFieldNombreCancion = new javax.swing.JTextField();
        jTextFieldDuracion = new javax.swing.JTextField();
        jTextFieldIdCancion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelInfo1 = new javax.swing.JLabel();
        jTextFieldEliminarCancion = new javax.swing.JTextField();
        jButtonEliminarCancion = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCancion = new javax.swing.JTable();
        jButtonEditarCancion = new javax.swing.JButton();
        jTextFieldIdAlbumParaCancion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonAlterCancion = new javax.swing.JButton();
        jComboBoxCancion = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Discografica:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Lider:");

        jLabelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInfo.setText("Sin conexión a la BBDD Discográfica.");

        jButtonInsertarAlbum.setText("Insertar Album");
        jButtonInsertarAlbum.setEnabled(false);
        jButtonInsertarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarAlbumActionPerformed(evt);
            }
        });

        jButtonEliminarAlbumIndividual.setText("Eliminar Album");
        jButtonEliminarAlbumIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarAlbumIndividualActionPerformed(evt);
            }
        });

        jTableAlbum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableAlbum);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("id:");

        jButtonCambiarAlbum.setText("Cambiar");
        jButtonCambiarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarAlbumActionPerformed(evt);
            }
        });

        jLabel9.setText("Genero:");

        jButtonAlterAlbum.setText("Atributo Album");
        jButtonAlterAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterAlbumActionPerformed(evt);
            }
        });

        jComboBoxAlterAlbum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "release_year", "num_canciones" }));

        javax.swing.GroupLayout AlbumLayout = new javax.swing.GroupLayout(Album);
        Album.setLayout(AlbumLayout);
        AlbumLayout.setHorizontalGroup(
            AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlbumLayout.createSequentialGroup()
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlbumLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIdAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AlbumLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonInsertarAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCambiarAlbum)))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldLider, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlbumLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AlbumLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDiscografica)
                        .addGap(8, 8, 8))))
            .addGroup(AlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(AlbumLayout.createSequentialGroup()
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AlbumLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AlbumLayout.createSequentialGroup()
                                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldEliminarAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(jComboBoxAlterAlbum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonAlterAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonEliminarAlbumIndividual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AlbumLayout.setVerticalGroup(
            AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlbumLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminarAlbumIndividual)
                    .addComponent(jTextFieldEliminarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterAlbum)
                    .addComponent(jComboBoxAlterAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertarAlbum)
                    .addComponent(jButtonCambiarAlbum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldLider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIdAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDiscografica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Album", Album);

        jButtonBorrarTablaCancion.setText("Borrar Tabla Cancion");
        jButtonBorrarTablaCancion.setEnabled(false);
        jButtonBorrarTablaCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTablaCancionActionPerformed(evt);
            }
        });

        jButtonInsertarCancion.setText("Insertar Cancion");
        jButtonInsertarCancion.setEnabled(false);
        jButtonInsertarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarCancionActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nombre:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Duracion:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Id_Cancion:");

        jLabelInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInfo1.setText("Sin conexión a la BBDD Discográfica.");

        jButtonEliminarCancion.setText("Eliminar Cancion");
        jButtonEliminarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarCancionActionPerformed(evt);
            }
        });

        jTableCancion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableCancion);

        jButtonEditarCancion.setText("Cambiar");
        jButtonEditarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarCancionActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("   Id_Album:");

        jButtonAlterCancion.setText("Atributo Cancion");
        jButtonAlterCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterCancionActionPerformed(evt);
            }
        });

        jComboBoxCancion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "escrita_por" }));

        jButton1.setText("Crear Tabla Grupo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CancionLayout = new javax.swing.GroupLayout(Cancion);
        Cancion.setLayout(CancionLayout);
        CancionLayout.setHorizontalGroup(
            CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CancionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonBorrarTablaCancion)
                        .addGap(30, 30, 30))
                    .addGroup(CancionLayout.createSequentialGroup()
                        .addComponent(jLabelInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(350, 350, 350))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CancionLayout.createSequentialGroup()
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CancionLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CancionLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldIdAlbumParaCancion)
                            .addComponent(jTextFieldIdCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonInsertarCancion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonEditarCancion, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(65, 65, 65))
                    .addGroup(CancionLayout.createSequentialGroup()
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CancionLayout.createSequentialGroup()
                                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldEliminarCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCancion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonAlterCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonEliminarCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(546, 546, 546)))
                        .addContainerGap(52, Short.MAX_VALUE))))
        );
        CancionLayout.setVerticalGroup(
            CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrarTablaCancion)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabelInfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEliminarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarCancion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterCancion)
                    .addComponent(jComboBoxCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldNombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldIdCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsertarCancion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarCancion)
                    .addComponent(jTextFieldIdAlbumParaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cancion", Cancion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarCancionActionPerformed
        // INSERTAR CANCION EN LA BBDD
        manager.insertarCancion(jTextFieldIdCancion.getText(),jTextFieldNombreCancion.getText(), jTextFieldDuracion.getText(), jTextFieldIdAlbumParaCancion.getText());
        mostrarTablaCancion();
        jLabelInfo.setText("Cancion insertada correctamente");
        jLabelInfo1.setText("Cancion insertada correctamente");
    }//GEN-LAST:event_jButtonInsertarCancionActionPerformed

    private void jButtonBorrarTablaCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTablaCancionActionPerformed
        // BORRAR TABLA CANCION
        manager.borrarTablaCancion();
        mostrarTablaCancion();
        jButtonBorrarTablaCancion.setEnabled(false);
        jLabelInfo.setText("La Tabla cancion a sido borrada correctamente");
        jLabelInfo1.setText("La Tabla cancion a sido creada correctamente");
    }//GEN-LAST:event_jButtonBorrarTablaCancionActionPerformed

    private void jButtonInsertarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarAlbumActionPerformed
        // INSERTAR ALBUM EN LA BBDD
        manager.insertarAlbum(jTextFieldIdAlbum.getText(), jTextFieldNombreAlbum.getText(), jTextFieldDiscografica.getText(), jTextFieldLider.getText(), jTextFieldGenero.getText());
        jLabelInfo.setText("Album insertado correctamente");
        jLabelInfo1.setText("Album insertado correctamente");
        mostrarTablaAlbum();
    }//GEN-LAST:event_jButtonInsertarAlbumActionPerformed

    private void jButtonEditarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarCancionActionPerformed
        // PARA EDITAR CANCIONES
        try {
            int filaCancion = jTableCancion.getSelectedRow();
            manager.editarCancion((jTableCancion.getValueAt(filaCancion, 0).toString()),
                    jTextFieldNombreCancion.getText(),
                    jTextFieldDuracion.getText());
            mostrarTablaCancion();
            jLabelInfo.setText("Canción modificada correctamente.");
            jLabelInfo1.setText("Canción modificada correctamente.");
        } catch (Exception ex) {
            jLabelInfo.setText("Error al modificar la canción.");
            jLabelInfo1.setText("Error al modificar la canción.");
        }
    }//GEN-LAST:event_jButtonEditarCancionActionPerformed

    private void jButtonEliminarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarCancionActionPerformed
        // PARA ELIMINAR CANCION
        manager.eliminarCancion(jTextFieldEliminarCancion.getText());
        mostrarTablaCancion();
    }//GEN-LAST:event_jButtonEliminarCancionActionPerformed

    private void jButtonEliminarAlbumIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarAlbumIndividualActionPerformed
        // PARA ELIMINAR UN ALBUM
        manager.eliminarAlbum(jTextFieldEliminarAlbum.getText());
        mostrarTablaAlbum();
    }//GEN-LAST:event_jButtonEliminarAlbumIndividualActionPerformed

    private void jButtonCambiarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarAlbumActionPerformed
        // PARA EDITAR DATOS ALBUM
        try {
            int filaAlbum = jTableAlbum.getSelectedRow();
            manager.editarAlbum((jTableAlbum.getValueAt(filaAlbum, 0).toString()),
                    jTextFieldNombreAlbum.getText(),
                    jTextFieldDiscografica.getText(),
                    jTextFieldLider.getText(),
                    jTextFieldGenero.getText());
            //AQUI ACTUALIZAMOS LAS DOS TABLAS YA QUE AL CAMBIAR
            //EL NOMBRE DEL ALBUM TAMBIEN SE CAMBIA EN CANCION
            mostrarTablaAlbum();
            mostrarTablaCancion();
            jLabelInfo.setText("Album modificado correctamente.");
            jLabelInfo1.setText("Album modificado correctamente.");
        } catch (Exception ex) {
            jLabelInfo.setText("Error al modificar el Album.");
            jLabelInfo1.setText("Error al modificar el Album.");
        }
    }//GEN-LAST:event_jButtonCambiarAlbumActionPerformed

    private void jButtonAlterCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterCancionActionPerformed
        // ALTER DE LA TABLA CANCION
        manager.crearAtributoCancion(jComboBoxCancion.getSelectedItem().toString());
    }//GEN-LAST:event_jButtonAlterCancionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // PARA CREAR UNA TABLA GRUPO (ALTER)
        manager.crearTablaGrupo();
        jLabelInfo.setText("Tabla grupo creada correctamente");
        jLabelInfo1.setText("Tabla grupo creada correctamente");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAlterAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterAlbumActionPerformed
        // ALTER DE LA TABLA ALBUM
        manager.crearAtributoAlbum(jComboBoxAlterAlbum.getSelectedItem().toString());
    }//GEN-LAST:event_jButtonAlterAlbumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAlbumCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAlbumCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAlbumCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAlbumCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAlbumCancion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Album;
    private javax.swing.JPanel Cancion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAlterAlbum;
    private javax.swing.JButton jButtonAlterCancion;
    private javax.swing.JButton jButtonBorrarTablaCancion;
    private javax.swing.JButton jButtonCambiarAlbum;
    private javax.swing.JButton jButtonEditarCancion;
    private javax.swing.JButton jButtonEliminarAlbumIndividual;
    private javax.swing.JButton jButtonEliminarCancion;
    private javax.swing.JButton jButtonInsertarAlbum;
    private javax.swing.JButton jButtonInsertarCancion;
    private javax.swing.JComboBox<String> jComboBoxAlterAlbum;
    private javax.swing.JComboBox<String> jComboBoxCancion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelInfo1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableAlbum;
    private javax.swing.JTable jTableCancion;
    private javax.swing.JTextField jTextFieldDiscografica;
    private javax.swing.JTextField jTextFieldDuracion;
    private javax.swing.JTextField jTextFieldEliminarAlbum;
    private javax.swing.JTextField jTextFieldEliminarCancion;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldIdAlbum;
    private javax.swing.JTextField jTextFieldIdAlbumParaCancion;
    private javax.swing.JTextField jTextFieldIdCancion;
    private javax.swing.JTextField jTextFieldLider;
    private javax.swing.JTextField jTextFieldNombreAlbum;
    private javax.swing.JTextField jTextFieldNombreCancion;
    // End of variables declaration//GEN-END:variables

    //METODOS PRIVADOS A PARTIR DE AQUI
    //PARA CONECTARSE A LA BBDD AL INICIAR LA APP
    private void conectarseADiscográfica() {
        manager.conection();
        jButtonInsertarAlbum.setEnabled(true);
        jButtonInsertarAlbum.setEnabled(true);
        ///
        jButtonBorrarTablaCancion.setEnabled(true);
        jButtonInsertarCancion.setEnabled(true);
        jButtonInsertarCancion.setEnabled(true);
        jLabelInfo.setText("Conectado con exito a Discográfica!");
        jLabelInfo1.setText("Conectado con exito a Discográfica!");
    }

    //PARA MOSTRAR LAS TABLAS
    private void mostrarTablaAlbum() {
        //SE CREA LA TABLA
        DefaultTableModel modelo = new DefaultTableModel();
        //AQUI SE INSERTA LA CONSULTA QUE VA EN POOLCONEXIONES
        //CONSULTA SIMPLE YA QUE COGEMOS TODOS LOS DATOS
        ResultSet rs = (ResultSet) manager.mostrarTabla("SELECT * FROM album ORDER BY id");
        try {
            //COGEMOS LOS NOMBRES DE LA COLUMNAS
            ResultSetMetaData metaDatos = rs.getMetaData();
            int numeroColumnas = metaDatos.getColumnCount();
            String[] etiquetas = new String[numeroColumnas];
            for (int i = 0; i < numeroColumnas; i++) {
                etiquetas[i] = metaDatos.getColumnLabel(i + 1);
                modelo.setColumnIdentifiers(etiquetas);
            }
            while (rs.next()) {
                //COGEMOS LOS DATOS DE LAS FILAS
                modelo.addRow(new Object[]{rs.getString("id"), rs.getString("Nombre_Album"),
                    rs.getString("Discografica"), rs.getString("Lider"), rs.getString("Genero")});
            }
            //SE INSERTAN LOS DATOS EN LA TABLA
            jTableAlbum.setModel(modelo);
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }

    //LO MISMO QUE PARA ALBUM PERO CON CACIONES
    private void mostrarTablaCancion() {
        //SE CREA LA TABLA
        DefaultTableModel modelo = new DefaultTableModel();
        try {
            //AQUI SE INSERTA LA CONSULTA QUE VA EN POOLCONEXIONES
            //SE COGE DE album.nombre DE LA TABLA ALBUM CUANDO
            //EL id_Album DE CANCION Y EL id DE ALBUM SEAN IGUALES
            ResultSet rs = (ResultSet) manager.mostrarTabla("SELECT cancion.*, album.Nombre_Album "
                    + "FROM cancion, album WHERE cancion.id_Album = album.id ORDER BY id_cancion;");
            //COGEMOS LOS NOMBRES DE LA COLUMNAS
            ResultSetMetaData metaDatos = rs.getMetaData();
            int numeroColumnas = metaDatos.getColumnCount();
            String[] etiquetas = new String[numeroColumnas];
            //COGEMOS LOS DATOS DE LAS FILAS
            for (int i = 0; i < numeroColumnas; i++) {
                etiquetas[i] = metaDatos.getColumnLabel(i + 1);
                modelo.setColumnIdentifiers(etiquetas);
            }
            while (rs.next()) {
                //COGEMOS LOS DATOS DE LAS FILAS
                modelo.addRow(new Object[]{rs.getInt("id_cancion"), rs.getString("Nombre"),
                    rs.getString("Duracion"), rs.getString("id_Album"), rs.getString("album.Nombre_Album")});
            }
            //SE INSERTAN LOS DATOS EN LA TABLA
            jTableCancion.setModel(modelo);
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }

    }

    // METODO PARA QUE SE AUTOCOMPLETEN LOS CAMPOS AL PULSAR UN DATO DE LA TABLA
    private void editar() {

        //EDITAR TABLA ALBUM
        //SOLO SE EDITA EL NOMBRE, LA DISCOGRAFICA, EL LIDER Y EL GENERO
        jTableAlbum.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                int filaAlbum = jTableAlbum.getSelectedRow();
                if (filaAlbum == -1) {
                    JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila.");
                } else {
                    String nombreAlbum = (String) jTableAlbum.getValueAt(filaAlbum, 1);
                    String discograficaAlbum = (String) jTableAlbum.getValueAt(filaAlbum, 2);
                    String liderAlbum = (String) jTableAlbum.getValueAt(filaAlbum, 3);
                    String generoAlbum = (String) jTableAlbum.getValueAt(filaAlbum, 4);
                    jTextFieldNombreAlbum.setText(nombreAlbum);
                    jTextFieldDiscografica.setText(discograficaAlbum);
                    jTextFieldLider.setText(liderAlbum);
                    jTextFieldGenero.setText(generoAlbum);
                }
            }
        });
        //EDITAR TABLA CANCIONES
        //SOLO SE EDITA EL NOMBRE Y LA DURACION DE LA CANCION
        jTableCancion.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent ev) {
                int filaCanciones = jTableCancion.getSelectedRow();
                if (filaCanciones == -1) {
                    JOptionPane.showMessageDialog(null, "No has seleccionado ninguna fila.");
                } else {
                    String nombreCancion = (String) jTableCancion.getValueAt(filaCanciones, 1);
                    String duracionCancion = (String) jTableCancion.getValueAt(filaCanciones, 2);
                    jTextFieldNombreCancion.setText(nombreCancion);
                    jTextFieldDuracion.setText(duracionCancion);
                }
            }
        });
    }
}
