/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexionbbdd;

/**
 *
 * @author aghsk
 */
public class VentanaAlbumCancion extends javax.swing.JFrame {

    PoolConexiones manager = new PoolConexiones();

    /**
     * Creates new form VentanaAlbumCancion
     */
    public VentanaAlbumCancion() {
        initComponents();
        conectarseADiscográfica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Album = new javax.swing.JPanel();
        jTextFieldNombreAlbum = new javax.swing.JTextField();
        jTextFieldDiscografica = new javax.swing.JTextField();
        jTextFieldLider = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jButtonDesconectar = new javax.swing.JButton();
        jButtonBorrarTablaAlbum = new javax.swing.JButton();
        jButtonCrearTablaAlbum = new javax.swing.JButton();
        jButtonAddColumnaTablaAlbum = new javax.swing.JButton();
        jButtonInsertarAlbum = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextFieldIdAlbum = new javax.swing.JTextField();
        Cancion = new javax.swing.JPanel();
        jButtonBorrarTablaCancion = new javax.swing.JButton();
        jButtonCrearTablaCancion = new javax.swing.JButton();
        jButtonAddColumnaTablaCancion = new javax.swing.JButton();
        jButtonInsertarCancion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextFieldIdCancion = new javax.swing.JTextField();
        jTextFieldNombreCancion = new javax.swing.JTextField();
        jTextFieldDuracion = new javax.swing.JTextField();
        jTextFieldFechaLanzamieto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelInfo1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAlbumCancion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Id:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Discografica:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Lider:");

        jLabelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInfo.setText("Sin conexión a la BBDD Discográfica.");

        jButtonDesconectar.setText("Desconectar");
        jButtonDesconectar.setEnabled(false);
        jButtonDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesconectarActionPerformed(evt);
            }
        });

        jButtonBorrarTablaAlbum.setText("Borrar Tabla Album");
        jButtonBorrarTablaAlbum.setEnabled(false);
        jButtonBorrarTablaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTablaAlbumActionPerformed(evt);
            }
        });

        jButtonCrearTablaAlbum.setText("Crear Tabla Album");
        jButtonCrearTablaAlbum.setEnabled(false);
        jButtonCrearTablaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearTablaAlbumActionPerformed(evt);
            }
        });

        jButtonAddColumnaTablaAlbum.setText("Añadir Atributo a Album");
        jButtonAddColumnaTablaAlbum.setEnabled(false);
        jButtonAddColumnaTablaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddColumnaTablaAlbumActionPerformed(evt);
            }
        });

        jButtonInsertarAlbum.setText("Insertar Album");
        jButtonInsertarAlbum.setEnabled(false);
        jButtonInsertarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarAlbumActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout AlbumLayout = new javax.swing.GroupLayout(Album);
        Album.setLayout(AlbumLayout);
        AlbumLayout.setHorizontalGroup(
            AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlbumLayout.createSequentialGroup()
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAddColumnaTablaAlbum)
                            .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldIdAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(AlbumLayout.createSequentialGroup()
                                    .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(AlbumLayout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldLider, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlbumLayout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(jTextFieldDiscografica, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jButtonInsertarAlbum)))
                        .addGap(54, 54, 54))
                    .addGroup(AlbumLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButtonDesconectar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBorrarTablaAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCrearTablaAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        AlbumLayout.setVerticalGroup(
            AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDesconectar)
                    .addComponent(jButtonBorrarTablaAlbum)
                    .addComponent(jButtonCrearTablaAlbum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelInfo)
                    .addComponent(jButtonAddColumnaTablaAlbum))
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlbumLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(AlbumLayout.createSequentialGroup()
                        .addGap(5, 259, Short.MAX_VALUE)
                        .addComponent(jButtonInsertarAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIdAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDiscografica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Album", Album);

        jButtonBorrarTablaCancion.setText("Borrar Tabla Cancion");
        jButtonBorrarTablaCancion.setEnabled(false);
        jButtonBorrarTablaCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTablaCancionActionPerformed(evt);
            }
        });

        jButtonCrearTablaCancion.setText("Crear Tabla Cancion");
        jButtonCrearTablaCancion.setEnabled(false);
        jButtonCrearTablaCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearTablaCancionActionPerformed(evt);
            }
        });

        jButtonAddColumnaTablaCancion.setText("Añadir a Cancion");
        jButtonAddColumnaTablaCancion.setEnabled(false);
        jButtonAddColumnaTablaCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddColumnaTablaCancionActionPerformed(evt);
            }
        });

        jButtonInsertarCancion.setText("Insertar Cancion");
        jButtonInsertarCancion.setEnabled(false);
        jButtonInsertarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarCancionActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nombre:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Id:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Duracion:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Release:");

        jLabelInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInfo1.setText("Sin conexión a la BBDD Discográfica.");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Album:");

        javax.swing.GroupLayout CancionLayout = new javax.swing.GroupLayout(Cancion);
        Cancion.setLayout(CancionLayout);
        CancionLayout.setHorizontalGroup(
            CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CancionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CancionLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAddColumnaTablaCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCrearTablaCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBorrarTablaCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(CancionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonInsertarCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldIdCancion)
                            .addComponent(jTextFieldNombreCancion)
                            .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldFechaLanzamieto)
                            .addComponent(jTextFieldAlbumCancion))))
                .addGap(18, 18, 18))
        );
        CancionLayout.setVerticalGroup(
            CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBorrarTablaCancion)
                    .addComponent(jLabelInfo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCrearTablaCancion)
                .addGap(18, 18, 18)
                .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CancionLayout.createSequentialGroup()
                        .addComponent(jButtonAddColumnaTablaCancion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addComponent(jButtonInsertarCancion)
                        .addGap(9, 9, 9)
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldAlbumCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIdCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFechaLanzamieto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cancion", Cancion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarAlbumActionPerformed
        // TODO add your handling code here:
        manager.insertarAlbum(jTextFieldIdAlbum.getText(), jTextFieldNombreAlbum.getText(), jTextFieldDiscografica.getText(), jTextFieldLider.getText());
        jLabelInfo.setText("Cancion insertada correctamente");
    }//GEN-LAST:event_jButtonInsertarAlbumActionPerformed

    private void jButtonAddColumnaTablaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddColumnaTablaAlbumActionPerformed
        // TODO add your handling code here:
        manager.addColumna();
        jButtonAddColumnaTablaAlbum.setEnabled(false);
        jLabelInfo.setText("Atributo anno_creacion añadido a la Tabla Grupo");
    }//GEN-LAST:event_jButtonAddColumnaTablaAlbumActionPerformed

    private void jButtonCrearTablaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearTablaAlbumActionPerformed
        // TODO add your handling code here:
        manager.crearTablaAlbum();
        jButtonAddColumnaTablaAlbum.setEnabled(true);
        jButtonCrearTablaAlbum.setEnabled(false);
        jLabelInfo.setText("La Tabla grupo a sido creada correctamente");
    }//GEN-LAST:event_jButtonCrearTablaAlbumActionPerformed

    private void jButtonBorrarTablaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTablaAlbumActionPerformed
        // TODO add your handling code here:
        manager.borrarTablaAlbum();
        jButtonCrearTablaAlbum.setEnabled(true);
        jButtonAddColumnaTablaAlbum.setEnabled(false);
        jLabelInfo.setText("La Tabla grupo a sido borrada correctamente");
    }//GEN-LAST:event_jButtonBorrarTablaAlbumActionPerformed

    private void jButtonDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesconectarActionPerformed
        // TODO add your handling code here:

        manager.cerrarConexion();
        jButtonDesconectar.setEnabled(false);
        jLabelInfo.setText("Desconectado con exito de Discográfica!");
        jLabelInfo1.setText("Desconectado con exito de Discográfica!");
    }//GEN-LAST:event_jButtonDesconectarActionPerformed

    private void jButtonBorrarTablaCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTablaCancionActionPerformed
        // TODO add your handling code here:
        manager.borrarTablaAlbum();
        jButtonCrearTablaAlbum.setEnabled(true);
        jButtonAddColumnaTablaAlbum.setEnabled(false);
        jLabelInfo.setText("La Tabla grupo a sido borrada correctamente");
        jLabelInfo1.setText("La Tabla grupo a sido creada correctamente");
    }//GEN-LAST:event_jButtonBorrarTablaCancionActionPerformed

    private void jButtonCrearTablaCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearTablaCancionActionPerformed
        // TODO add your handling code here:
        manager.crearTablaAlbum();
        jButtonAddColumnaTablaAlbum.setEnabled(true);
        jButtonCrearTablaAlbum.setEnabled(false);
        jLabelInfo.setText("La Tabla grupo a sido creada correctamente");
        jLabelInfo1.setText("La Tabla grupo a sido creada correctamente");

    }//GEN-LAST:event_jButtonCrearTablaCancionActionPerformed

    private void jButtonAddColumnaTablaCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddColumnaTablaCancionActionPerformed
        // TODO add your handling code here:
        manager.addColumna();
        jButtonAddColumnaTablaAlbum.setEnabled(false);
        jLabelInfo.setText("Atributo anno_creacion añadido a la Tabla Grupo");
        jLabelInfo1.setText("Atributo anno_creacion añadido a la Tabla Grupo");
    }//GEN-LAST:event_jButtonAddColumnaTablaCancionActionPerformed

    private void jButtonInsertarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarCancionActionPerformed
        // TODO add your handling code here:
        manager.insertarCancion(jTextFieldIdCancion.getText(), jTextFieldNombreCancion.getText(), jTextFieldDuracion.getText(), jTextFieldFechaLanzamieto.getText(), jTextFieldAlbumCancion.getText());
        jLabelInfo.setText("Cancion insertada correctamente");
        jLabelInfo1.setText("Cancion insertada correctamente");
    }//GEN-LAST:event_jButtonInsertarCancionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAlbumCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAlbumCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAlbumCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAlbumCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAlbumCancion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Album;
    private javax.swing.JPanel Cancion;
    private javax.swing.JButton jButtonAddColumnaTablaAlbum;
    private javax.swing.JButton jButtonAddColumnaTablaCancion;
    private javax.swing.JButton jButtonBorrarTablaAlbum;
    private javax.swing.JButton jButtonBorrarTablaCancion;
    private javax.swing.JButton jButtonCrearTablaAlbum;
    private javax.swing.JButton jButtonCrearTablaCancion;
    private javax.swing.JButton jButtonDesconectar;
    private javax.swing.JButton jButtonInsertarAlbum;
    private javax.swing.JButton jButtonInsertarCancion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelInfo1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextFieldAlbumCancion;
    private javax.swing.JTextField jTextFieldDiscografica;
    private javax.swing.JTextField jTextFieldDuracion;
    private javax.swing.JTextField jTextFieldFechaLanzamieto;
    private javax.swing.JTextField jTextFieldIdAlbum;
    private javax.swing.JTextField jTextFieldIdCancion;
    private javax.swing.JTextField jTextFieldLider;
    private javax.swing.JTextField jTextFieldNombreAlbum;
    private javax.swing.JTextField jTextFieldNombreCancion;
    // End of variables declaration//GEN-END:variables

    private void conectarseADiscográfica() {
        manager.conection();
        jButtonDesconectar.setEnabled(true);
        jButtonBorrarTablaAlbum.setEnabled(true);
        jButtonAddColumnaTablaAlbum.setEnabled(true);
        jButtonDesconectar.setEnabled(true);
        jButtonInsertarAlbum.setEnabled(true);
        jButtonInsertarCancion.setEnabled(true);
        jLabelInfo.setText("Conectado con exito a Discográfica!");
        jLabelInfo1.setText("Conectado con exito a Discográfica!");
    }
}
